seed: 42
device: "cuda"

dataset:
  name: "cifar100"
  root: "./data/cifar100"
  num_workers: 8
  batch_size: 128
  pin_memory: true

model:
  name: "mobilenet_v3_large"
  num_classes: 100

optimizer:
  name: "sgd"
  lr: 0.1
  weight_decay: 0.0005

scheduler:
  name: "cosine"
  max_epochs: 50
  min_lr: 1e-6

augment:
  train:
    - {name: "Resize", size: 224}   # 추가된 부분
    - {name: "RandomCrop", size: 32, padding: 4}
    - {name: "RandomHorizontalFlip", p: 0.5}
    - {name: "RandAugment", n: 2, m: 9}
    - {name: "ToTensor", }
    - {name: "Normalize", mean: [0.5071,0.4867,0.4408], std: [0.2675,0.2565,0.2761]} # cifar100
  eval:
    - {name: "ToTensor", }
    - {name: "Normalize", mean: [0.5071,0.4867,0.4408], std: [0.2675,0.2565,0.2761]} # cifar100

loss:
  name: "cross_entropy"

logger:
  name: "simple"

trainer:
  name : "classifier_trainer"
  epochs: 50
  grad_clip: 1.0
  amp: true             # mixed precision
  val_interval: 1       # 에폭 단위 검증

checkpoint_saver:
  save_dir: "checkpoints/cifar100/mobilenet_v3_large"
  save_best: true
  save_last: false