seed: 42
device: "cuda"

dataset:
  name: "cifar10"
  root: "./data"
  num_workers: 8
  batch_size: 128
  pin_memory: true

model:
  name: "resnet_mini_v2_28"
  num_classes: 10

optimizer:
  name: "sgd"
  lr: 3e-4
  weight_decay: 0.05

scheduler:
  name: "cosine"
  max_epochs: 20
  min_lr: 1e-6

augment:
  train:
    - {name: "RandomCrop", size: 32, padding: 4}
    - {name: "RandomHorizontalFlip", p: 0.5}
    - {name: "RandAugment", n: 2, m: 9}
    - {name: "ToTensor", }
    - {name: "Normalize", mean: [0.491,0.482,0.447], std: [0.247,0.243,0.262]}
  eval:
    - {name: "ToTensor", }
    - {name: "Normalize", mean: [0.491,0.482,0.447], std: [0.247,0.243,0.262]}
  # batch_train:
  #   name: "mixcut"          # "mixup" | "cutmix" | "mixcut"
  #   mixup_alpha: 0.2
  #   cutmix_alpha: 1.0
  #   p: 1.0                  # 적용 확률
  #   switch_prob: 0.5        # mixup/cutmix 중 선택 확률 (mixcut일 때 사용)

loss:
  name: "cross_entropy"

logger:
  name: "wandb"   # "wandb" 도 가능
  project : "cifar10-image-classification"
# log_dir: "./runs"

trainer:
  name : "image_trainer"
  epochs: 5
  grad_clip: 1.0
  amp: true             # mixed precision
  val_interval: 1       # 에폭 단위 검증
  save_best: true