seed: 42
device: "cuda"

dataset:
  name: "cifar10"
  root: "./data/cifar10"
  num_workers: 8
  batch_size: 128
  pin_memory: true

model:
  name: "resnet_mini_v2_28"
  num_classes: 10

optimizer:
  name: "sgd"
  lr: 0.1
  weight_decay: 0.0005

scheduler:
  name: "cosine"
  max_epochs: 50
  min_lr: 1e-6

augment:
  train:
    - {name: "RandomCrop", size: 32, padding: 4}
    - {name: "RandomHorizontalFlip", p: 0.5}
    - {name: "RandAugment", n: 2, m: 9}
    - {name: "ToTensor", }
    - {name: "Normalize", mean: [0.491,0.482,0.447], std: [0.247,0.243,0.262]} # cifar10
  eval:
    - {name: "ToTensor", }
    - {name: "Normalize", mean: [0.491,0.482,0.447], std: [0.247,0.243,0.262]} # cifar10

loss:
  name: "cross_entropy"

logger:
  name: "simple"

trainer:
  name : "image_classifier_trainer"
  epochs: 50
  grad_clip: 1.0
  amp: true             # mixed precision
  val_interval: 1       # 에폭 단위 검증

checkpoint_saver:
  save_dir: "checkpoints/resnet_mini_v2_28"
  save_best: true
  save_last: false