seed: 42
device: "cuda"

dataset:
  name: "cifar100"
  root: "./data/cifar100"
  num_workers: 8
  batch_size: 256
  pin_memory: true

model:
  name: "resnet_mini_v2_41"
  num_classes: 100

optimizer:
  name: "sgd"
  lr: 0.2
  weight_decay: 0.0005

scheduler:
  name: "cosine_schedule_with_warmup"
  num_warmup_steps: 6000
  num_training_steps: 120000
  num_cycles: 0.5

augment:
  train:
    - {name: "RandomCrop", size: 32, padding: 4}
    - {name: "RandomHorizontalFlip", p: 0.5}
    - {name: "RandAugment", n: 2, m: 9}
    - {name: "ToTensor", }
    - {name: "RandomErasing", p: 0.5, scale: [0.02, 0.33], ratio: [0.3, 3.3], value: 0, same_on_batch: False}
    - {name: "Normalize", mean: [0.5071,0.4867,0.4408], std: [0.2675,0.2565,0.2761]} # cifar100
  eval:
    - {name: "ToTensor", }
    - {name: "Normalize", mean: [0.5071,0.4867,0.4408], std: [0.2675,0.2565,0.2761]} # cifar100

batch_aug:
  name: "mixcut"
  mixup_alpha: 0.2
  cutmix_alpha: 1.0
  p: 1.0
  switch_prob: 0.5
  num_classes: 100

loss:
  name: "label_smoothing"

logger:
  name: "simple"

trainer:
  name : "classifier_trainer"
  epochs: 600
  grad_clip: 1.0
  amp: true             # mixed precision
  val_interval: 1       # 에폭 단위 검증

checkpoint_saver:
  save_dir: "/content/drive/MyDrive/Colab_sample_checkpoints/cifar100/resnet/resnet41_cifar100_sgd_aug_600"
  save_best: true
  save_last: false